
/**
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/19/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of Classifiedproduct
 *
 * @constructor
 */
Classifiedproduct = function (obj) {
    if(!obj) {
        this.breadcrumbs = null;     
        this.category = null;     
        this.cleanTitle = null;     
        this.usdaCode = null;     
    } else {
        this.breadcrumbs = (obj.breadcrumbs !== undefined && obj.breadcrumbs !== null)? obj.breadcrumbs : null;
        this.category = (obj.category !== undefined && obj.category !== null)? obj.category : null;
        this.cleanTitle = (obj.cleanTitle !== undefined && obj.cleanTitle !== null)? obj.cleanTitle : null;
        this.usdaCode = (obj.usdaCode !== undefined && obj.usdaCode !== null)? obj.usdaCode : null;
    }
};

Classifiedproduct.prototype = new BaseModel();
Classifiedproduct.prototype.constructor = Classifiedproduct;

/**
 * TODO: Write general description for this method
 *
 * @return {array}
 */
Classifiedproduct.prototype.getBreadcrumbs = function() {
    return this.breadcrumbs;
};

/**
 * Setter for Breadcrumbs
 * 
 * @param {array} value 
 */
Classifiedproduct.prototype.setBreadcrumbs = function(value) {
    this.breadcrumbs = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Classifiedproduct.prototype.getCategory = function() {
    return this.category;
};

/**
 * Setter for Category
 * 
 * @param {string} value 
 */
Classifiedproduct.prototype.setCategory = function(value) {
    this.category = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
Classifiedproduct.prototype.getCleanTitle = function() {
    return this.cleanTitle;
};

/**
 * Setter for CleanTitle
 * 
 * @param {string} value 
 */
Classifiedproduct.prototype.setCleanTitle = function(value) {
    this.cleanTitle = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
Classifiedproduct.prototype.getUsdaCode = function() {
    return this.usdaCode;
};

/**
 * Setter for UsdaCode
 * 
 * @param {int} value 
 */
Classifiedproduct.prototype.setUsdaCode = function(value) {
    this.usdaCode = value;
};


module.exports = Classifiedproduct;
