
/**
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/19/2017
 */
var BaseModel = require("./BaseModel");
/**
 * Creates an instance of FindByIngredientsModel
 *
 * @constructor
 */
FindByIngredientsModel = function (obj) {
    if(!obj) {
        this.id = null;     
        this.image = null;     
        this.likes = null;     
        this.missedIngredientCount = null;     
        this.title = null;     
        this.usedIngredientCount = null;     
    } else {
        this.id = (obj.id !== undefined && obj.id !== null)? obj.id : null;
        this.image = (obj.image !== undefined && obj.image !== null)? obj.image : null;
        this.likes = (obj.likes !== undefined && obj.likes !== null)? obj.likes : null;
        this.missedIngredientCount = (obj.missedIngredientCount !== undefined && obj.missedIngredientCount !== null)? obj.missedIngredientCount : null;
        this.title = (obj.title !== undefined && obj.title !== null)? obj.title : null;
        this.usedIngredientCount = (obj.usedIngredientCount !== undefined && obj.usedIngredientCount !== null)? obj.usedIngredientCount : null;
    }
};

FindByIngredientsModel.prototype = new BaseModel();
FindByIngredientsModel.prototype.constructor = FindByIngredientsModel;

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
FindByIngredientsModel.prototype.getId = function() {
    return this.id;
};

/**
 * Setter for Id
 * 
 * @param {int} value 
 */
FindByIngredientsModel.prototype.setId = function(value) {
    this.id = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
FindByIngredientsModel.prototype.getImage = function() {
    return this.image;
};

/**
 * Setter for Image
 * 
 * @param {string} value 
 */
FindByIngredientsModel.prototype.setImage = function(value) {
    this.image = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
FindByIngredientsModel.prototype.getLikes = function() {
    return this.likes;
};

/**
 * Setter for Likes
 * 
 * @param {int} value 
 */
FindByIngredientsModel.prototype.setLikes = function(value) {
    this.likes = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
FindByIngredientsModel.prototype.getMissedIngredientCount = function() {
    return this.missedIngredientCount;
};

/**
 * Setter for MissedIngredientCount
 * 
 * @param {int} value 
 */
FindByIngredientsModel.prototype.setMissedIngredientCount = function(value) {
    this.missedIngredientCount = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {string}
 */
FindByIngredientsModel.prototype.getTitle = function() {
    return this.title;
};

/**
 * Setter for Title
 * 
 * @param {string} value 
 */
FindByIngredientsModel.prototype.setTitle = function(value) {
    this.title = value;
};

/**
 * TODO: Write general description for this method
 *
 * @return {int}
 */
FindByIngredientsModel.prototype.getUsedIngredientCount = function() {
    return this.usedIngredientCount;
};

/**
 * Setter for UsedIngredientCount
 * 
 * @param {int} value 
 */
FindByIngredientsModel.prototype.setUsedIngredientCount = function(value) {
    this.usedIngredientCount = value;
};


module.exports = FindByIngredientsModel;
