/**
 * SpoonacularAPILib
 *
 * This file was automatically generated by APIMATIC v2.0 ( https://apimatic.io ) on 01/19/2017
 */

var Configuration = {
    //The base Uri for API calls
    BASEURI : "https://spoonacular-recipe-food-nutrition-v1.p.mashape.com",

    //The Mashape application you want to use for this session.
    //TODO: Replace the XMashapeKey with an appropriate value
    xMashapeKey : "TODO: Replace"

};

module.exports = Configuration;
